version: '2'
services:
  spark:
    image: docker.io/denisog/bitnami-spark:3.3
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - ./crime-in-uk-trg:/work/jobs
      - ./data:/work/data/source
      - ./crime-in-uk-trg/resources/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
  spark-worker:
    image: docker.io/denisog/bitnami-spark:3.3
    user: root
    volumes:
      - ./crime-in-uk-trg:/work/jobs
      - ./data/crimes:/work/data/source
      - ./crime-in-uk-trg/resources/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no